feedback_url:
  type: string
  default: ''
feedback_descriptions:
  type: list
  default:
    This is the Global iHub, a friendly forum built by ICIJ as a secure online collaboration tool.|
    ICIJ uses the platform to coordinate its reporting projects. Yet even those not involved in projects can use the I-Hub to communicate securely with other investigative journalists all around the world.|
    This tool is still under active development and we're happy to welcome your feedback.
